services:
  node_app:
    image: node_boilerplate:latest
    container_name: node_boilerplate
    restart: always
    networks:
      - webproxy
    expose:
      - "3000"
    environment:
      - NODE_ENV=production

networks:
  webproxy:
    external: true 
