services:
  node_app:
    image: node_boilerplate:latest
    container_name: node_boilerplate
    restart: always
    ports:
      - "3002:8001"
    environment:
      - NODE_ENV=production
    networks:
      - webproxy

networks:
  webproxy:
    external: true

  
